version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "monthly"
    ignored_updates:
      # 4.x breaks autocapitalize
      - match:
          dependency_name: "ember-bootstrap"
          version_requirement: "*"
      # Update core ember dependencies with ember-cli-update instead
      - match:
          dependency_name: "ember-cli"
          version_requirement: "*"
      - match:
          dependency_name: "ember-data"
          version_requirement: "*"
      - match:
          dependency_name: "ember-source"
          version_requirement: "*"
